workflows:
  expo-ios-workflow:
    name: Expo iOS Build (No Mac Required)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 20.19.4
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm ci
      - name: Build iOS IPA with EAS
        script: |
          export EXPO_TOKEN=$EXPO_TOKEN
          eas whoami
          eas build --platform ios --profile production --non-interactive
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - your-email@example.com  # Change this to your email
        notify:
          success: true
          failure: true

  expo-ios-preview:
    name: Expo iOS Preview Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 20.19.4
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm ci
      - name: Build iOS Preview
        script: |
          export EXPO_TOKEN=$EXPO_TOKEN
          eas whoami
          eas build --platform ios --profile preview --non-interactive
    artifacts:
      - "*.ipa"
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
